### ISSUE TITLE
Copy of is-a.dev

### ISSUE THREAD

**Issue by SkyExploreWasTaken** [isdevme/isdevme#1]
Just a question, why YOU COPIED is-a.dev ? We can see it here : 
![image](https://github.com/user-attachments/assets/521ac693-1a95-476c-a0dc-6d215519ba39)
"go to the is-a.dev registration repository"

**Comment by SkyExploreWasTaken** [comment]
If you copy, make sure people can't see it.

**Comment by razinrayees** [comment]
> Thank you for your feedback. I want to clarify that our main intention is to offer a free subdomain service specifically for developers. We used [is-a.dev] as a reference to understand the functionality and user experience we wanted to provide, but we have worked to ensure our implementation is original and tailored to our own approach.
> 
> Our goal is to support the development community by offering a free tool that helps with subdomain management. We appreciate your understanding and are open to any suggestions for improvement.
> 
> Best regards,
> isdev.me team
